export PYTHONPATH=./
export MODEL_CONFIG="configs/fullattn_tiny/config_swa_345M.json"
export CORPUS_PATH="${CORPUS_PATH:-data/dolma3_mix-6T-1025-partial-tokenized}"
export MAX_SEQ_LEN=8192
export WANDB_NAME="swa_345M_dist"
export OUTPUT_DIR="${OUTPUT_DIR:-outputs/checkpoints/swa_345M_dist}"
export GRADIENT_CKPT=false
export MICRO_BATCH_SIZE=4
export GLOBAL_BATCH_SIZE=128
bash scripts/pretrain/pretrain_ruler_task_5per_345M_dist.sh